name: sample_app
description: "Sample app to test flutter_auth_package"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.8
  build_runner: ^2.0.4
  

  flutter_app_info: ^2.0.0
  flutter_web_auth_2: ^3.1.1
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1
  unique_identifier: ^0.3.0  # only works on android ios
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  fast_rsa: ^3.6.1
  basic_utils: ^5.7.0
  flutter_curl: ^0.3.0
  logger: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_auth_package:
    git:
      url: https://github.com/zebratechnologies/SWS_flutter_auth_package.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.1


flutter:

  uses-material-design: true